name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:22.20.0
      options: --user 1001
    strategy:
      fail-fast: false
      matrix:
        group:
          - name: group-1
            specs: "cypress/tests/ui/transaction-feeds.spec.ts"
          - name: group-2
            specs: "cypress/tests/ui/new-transaction.spec.ts,cypress/tests/ui/notifications.spec.ts"
          - name: group-3
            specs: "cypress/tests/ui/auth.spec.ts,cypress/tests/ui/bankaccounts.spec.ts,cypress/tests/ui/transaction-view.spec.ts,cypress/tests/ui/user-settings.spec.ts"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - run: yarn types
      - run: yarn lint
      - run: yarn test:unit:ci
      - run: yarn build:ci

      - name: Run Cypress E2E tests (${{ matrix.group.name }})
        uses: cypress-io/github-action@v6
        with:
          start: yarn start:ci
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          spec: ${{ matrix.group.specs }}
          config-file: cypress.config.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}